name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:23.0.5
        options: --privileged # Docker-in-Docker 지원

    env:
      DOCKER_IMAGE: junwoo5914/paaran

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: SignIn to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.PUBLIC_DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.PUBLIC_DOCKER_PASSWORD }}
        run: echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build Docker images
        run: docker build -t paaran-web:latest -f Dockerfile .

      - name: Tag and push Docker images
        run: |
          docker tag paaran-web:latest "${{ env.DOCKER_IMAGE }}:web-${{ github.ref_name }}"
          docker push "${{ env.DOCKER_IMAGE }}:web-${{ github.ref_name }}"
